[package]
name = "warpgate-protocol-rdp"
version = "0.23.4"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
futures.workspace = true
ironrdp = { version = "0.17", features = [
    "cliprdr",
    "connector",
    "session",
    "graphics",
    "input",
    "dvc",
    "displaycontrol",
] }
ironrdp-server = "0.13"
ironrdp-tokio = "0.10"
openssl = { version = "0.10", optional = true, features = ["vendored"] }
rustls = { version = "0.23", default-features = false, features = [
    "ring",
    "std",
    "tls12",
    "logging",
] }
rustls-native-certs = "0.8"
rustls-pemfile = "2"
tokio = { workspace = true, features = [
    "io-util",
    "net",
    "sync",
    "macros",
    "time",
    "rt",
    "fs",
] }
tokio-openssl = { version = "0.6", optional = true }
tokio-stream.workspace = true
tracing.workspace = true
uuid.workspace = true
warpgate-common = { path = "../warpgate-common", default-features = false }
warpgate-core = { path = "../warpgate-core", default-features = false }
warpgate-db-entities = { path = "../warpgate-db-entities", default-features = false }
warpgate-desktop-auth = { path = "../warpgate-desktop-auth" }
warpgate-desktop-ui = { path = "../warpgate-desktop-ui" }
warpgate-tls = { path = "../warpgate-tls" }
x509-cert = { version = "0.2", default-features = false, features = ["std"] }

[features]
openssl-tls = [
    "dep:openssl",
    "dep:tokio-openssl",
]
