<script lang="ts">
    import { faRefresh } from '@fortawesome/free-solid-svg-icons'
    import {
        Button,
        Form,
        FormGroup,
        Input,
        Modal,
        ModalBody,
        ModalFooter,
    } from '@sveltestrap/sveltestrap'
    import base32Encode from 'base32-encode'
    import CopyButton from 'common/CopyButton.svelte'
    import * as OTPAuth from 'otpauth'
    import QRCode from 'qrcode'
    import Fa from 'svelte-fa'

    interface Props {
        isOpen: boolean
        username: string
        create: (secretKey: number[]) => void
    }

    let { isOpen = $bindable(true), username, create }: Props = $props()
    let secretKey: number[] = $state([])
    let qrImage: HTMLImageElement | undefined = $state()
    let totpUri = $state('')
    let totpValidationValue: string | undefined = $state()
    let field: HTMLInputElement | undefined = $state()
    let validated = $state(false)
    let totpValid = $state(false)
    let validationFeedback = $state<string | undefined>()

    const totp = $state(
        new OTPAuth.TOTP({
            issuer: 'Warpgate',
            digits: 6,
            period: 30,
            algorithm: 'SHA1',
        }),
    )

    function _validate(): boolean {
        if (totpValidationValue) {
            totp.secret ??= OTPAuth.Secret.fromBase32(
                encodeTotpSecret(secretKey),
            )
            totpValid =
                totp.validate({ token: totpValidationValue, window: 1 }) !==
                null

            if (!totpValid) {
                validationFeedback = 'The TOTP code is not valid'
            } else {
                validationFeedback = undefined
            }

            return totpValid
        }
        return true
    }

    function generateNewTotpKey() {
        secretKey = Array.from({ length: 32 }, () =>
            Math.floor(Math.random() * 255),
        )
    }

    /**
     * Generates a TOTP (Time-based One-Time Password) secret key encoded in base32.
     *
     * @param {UserTotpCredential} cred - The credential containing a key for TOTP generation.
     * @return {string} The base32 encoded TOTP secret key.
     */
    function encodeTotpSecret(secretKey: number[]): string {
        return base32Encode(new Uint8Array(secretKey), 'RFC4648')
    }

    $effect(() => {
        if (!secretKey.length) {
            generateNewTotpKey()
        }

        totp.label = username
        totp.secret = OTPAuth.Secret.fromBase32(encodeTotpSecret(secretKey))
        totpUri = totp.toString()

        QRCode.toDataURL(
            totpUri,
            (err: Error | null | undefined, imageUrl: string) => {
                if (err) {
                    return
                }
                if (qrImage) {
                    qrImage.src = imageUrl
                }
            },
        )

        _validate()
    })

    function _save() {
        if (!secretKey) {
            return
        }
        isOpen = false
        create(secretKey)
    }

    function _cancel() {
        isOpen = false
    }
</script>

<Modal toggle={_cancel} {isOpen} on:open={() => field?.focus()}>
    <Form
        {validated}
        on:submit={e => {
        _save()
        e.preventDefault()
    }}
    >
        <ModalBody>
            <div class="d-flex gap-4 layout ms-2">
                <div>
                    <img
                        class="qr mb-3 mt-2"
                        bind:this={qrImage}
                        alt="OTP QR code"
                    >
                    <div
                        class="d-flex ms-2 me-2 mb-4 gap-3 justify-content-center"
                    >
                        <CopyButton
                            class="d-flex align-items-center w-100"
                            color="secondary"
                            text={totpUri}
                            label="Copy"
                        />
                    </div>
                </div>
                <div class="mt-2">
                    <ol>
                        <li class="mb-2">
                            Install a TOTP authenticator app, such as
                            <em>Microsoft Authenticator</em>, or use your
                            password manager.
                        </li>
                        <li class="mb-2">
                            Initialize it using the code on the left.
                        </li>
                        <li class="mb-2">
                            <div>
                                Type the one-time password generated by the app
                                below:
                            </div>
                            <FormGroup
                                floating
                                class="mt-3 mb-4"
                                label="One-time password"
                                spacing="0"
                            >
                                <Input
                                    required
                                    autofocus
                                    bind:feedback={validationFeedback}
                                    bind:value={totpValidationValue}
                                    valid={totpValid}
                                    invalid={!totpValid}
                                    pattern={'\\d{6}'}
                                    inputmode="numeric"
                                    on:change={_validate}
                                    on:keyup={_validate}
                                />
                            </FormGroup>
                        </li>
                    </ol>
                </div>
            </div>
        </ModalBody>
        <ModalFooter>
            <Button
                class="modal-button"
                color="primary"
                disabled={!totpValid}
                on:click={() => validated = true}
            >
                Confirm
            </Button>

            <Button class="modal-button" color="danger" on:click={_cancel}>
                Cancel
            </Button>
        </ModalFooter>
    </Form>
</Modal>

<style lang="scss">
    .qr {
        border-radius: 5px;
        max-width: 150px;
        margin: auto;
        display: block;
    }

    @media (max-width: 768px) {
        .layout {
            flex-direction: column;
            align-items: center;
        }
    }
</style>
