#!/bin/bash
# Fix TypeScript compilation issues in OpenAPI generated types
# The OpenAPI generator generates code that uses "interface extends" on union types,
# which is invalid in TypeScript. This script patches those cases to use type intersections instead.

set -e

API_CLIENT_DIR="$1"

if [ -z "$API_CLIENT_DIR" ]; then
    echo "Usage: $0 <api-client-directory>"
    exit 1
fi

TARGET_FILE="$API_CLIENT_DIR/src/models/TargetOptionsTargetRemoteRunOptions.ts"

if [ -f "$TARGET_FILE" ]; then
    echo "Patching $TARGET_FILE..."
    
    # Replace the interface extends with a type intersection
    cat > "$TARGET_FILE" << 'EOF'
/* tslint:disable */
/* eslint-disable */
/**
 * Warpgate Web Admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TargetRemoteRunOptions } from './TargetRemoteRunOptions';
import {
    TargetRemoteRunOptionsFromJSON,
    TargetRemoteRunOptionsFromJSONTyped,
    TargetRemoteRunOptionsToJSON,
} from './TargetRemoteRunOptions';

/**
 * @export
 */
export const TargetOptionsTargetRemoteRunOptionsKindEnum = {
    RemoteRun: 'RemoteRun'
} as const;
export type TargetOptionsTargetRemoteRunOptionsKindEnum = typeof TargetOptionsTargetRemoteRunOptionsKindEnum[keyof typeof TargetOptionsTargetRemoteRunOptionsKindEnum];

/**
 * 
 * @export
 * @type TargetOptionsTargetRemoteRunOptions
 */
export type TargetOptionsTargetRemoteRunOptions = TargetRemoteRunOptions & {
    /**
     * 
     * @type {string}
     * @memberof TargetOptionsTargetRemoteRunOptions
     */
    kind: TargetOptionsTargetRemoteRunOptionsKindEnum;
};

/**
 * Check if a given object implements the TargetOptionsTargetRemoteRunOptions interface.
 */
export function instanceOfTargetOptionsTargetRemoteRunOptions(value: object): value is TargetOptionsTargetRemoteRunOptions {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    return true;
}

export function TargetOptionsTargetRemoteRunOptionsFromJSON(json: any): TargetOptionsTargetRemoteRunOptions {
    return TargetOptionsTargetRemoteRunOptionsFromJSONTyped(json, false);
}

export function TargetOptionsTargetRemoteRunOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TargetOptionsTargetRemoteRunOptions {
    if (json == null) {
        return json;
    }
    return {
        ...TargetRemoteRunOptionsFromJSONTyped(json, ignoreDiscriminator),
        'kind': json['kind'],
    } as TargetOptionsTargetRemoteRunOptions;
}

export function TargetOptionsTargetRemoteRunOptionsToJSON(value?: TargetOptionsTargetRemoteRunOptions | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...TargetRemoteRunOptionsToJSON(value as TargetRemoteRunOptions),
        'kind': value['kind'],
    };
}
EOF
    echo "Patched successfully!"
else
    echo "Target file not found: $TARGET_FILE (this is OK if RemoteRun is not in the schema)"
fi
