{{- with (include "warpgate.configMapName" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ . }}
  labels:
    {{- include "warpgate.labels" $ | nindent 4 }}
data:
  warpgate.yaml: |
  {{ $.Values.overrides_config | default (include "warpgate.config" $) | nindent 4 }}
{{- end }}
