name: Biome

on: [pull_request]
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: biomejs/setup-biome@v2
        with:
          version: 2.5.9

      - name: Biome CI
        run: biome ci
        working-directory: warpgate-web
