name: Cargo Deny
permissions:
  contents: read

on: [push, pull_request]

jobs:
  cargo-deny:
    name: cargo-deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install cargo-deny
        run: cargo install --locked cargo-deny@0.18.9

      - name: cargo-deny check
        run: |
          cargo deny --version
          cargo deny check
