name: Cargo fmt-toml

on: [push, pull_request]
permissions:
    contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    fmt-toml:
        name: cargo-fmt-toml
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

            - name: Install cargo-fmt-toml
              run: cargo install --locked cargo-fmt-toml@0.0.16

            - name: cargo fmt-toml --check
              run: cargo fmt-toml --check
